version: '3.9'

services:
  web:
    build: .
    container_name: django_basic_web
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: django_basic_db
    environment:
      MYSQL_ROOT_PASSWORD: root1234
      MYSQL_DATABASE: django_basic
      MYSQL_USER: root
      MYSQL_PASSWORD: root1234
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
