# Generated by Django 4.2.16 on 2024-12-18 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invent_app', '0002_products_is_food_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='picture',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
